# Generated by Django 5.2.4 on 2025-07-29 04:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=255, unique=True)),
                ("user_id", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("merchant_id", models.CharField(max_length=255)),
                ("payment_method", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("flagged", "Flagged"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("fraud_score", models.FloatField(blank=True, null=True)),
                ("risk_level", models.CharField(blank=True, max_length=20)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("device_fingerprint", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction_id"], name="transaction_transac_fee96f_idx"
                    ),
                    models.Index(
                        fields=["user_id"], name="transaction_user_id_b60ed6_idx"
                    ),
                    models.Index(
                        fields=["status"], name="transaction_status_71abbb_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="transaction_created_67ce7b_idx"
                    ),
                ],
            },
        ),
    ]
