import uuid

from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class FraudRule(models.Model):
    """Fraud detection rules."""

    ACTION_CHOICES = [
        ("flag", "Flag for Review"),
        ("decline", "Decline Transaction"),
        ("alert", "Send Alert"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    conditions = models.JSONField()  # Store rule conditions as JSON
    action = models.CharField(max_length=20, choices=ACTION_CHOICES)
    is_active = models.BooleanField(default=True)
    priority = models.IntegerField(default=1)

    # Ownership
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="fraud_rules"
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["priority", "name"]

    def __str__(self):
        return self.name


class FraudAlert(models.Model):
    """Fraud alerts generated by the system."""

    SEVERITY_CHOICES = [
        ("low", "Low"),
        ("medium", "Medium"),
        ("high", "High"),
        ("critical", "Critical"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    transaction_id = models.CharField(max_length=255)
    alert_type = models.CharField(max_length=100)
    severity = models.CharField(max_length=20, choices=SEVERITY_CHOICES)
    message = models.TextField()
    is_resolved = models.BooleanField(default=False)

    # Ownership
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="fraud_alerts"
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    resolved_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"Alert: {self.alert_type} - {self.transaction_id}"
